export const APP_CONSTANTS = {
  ACCOUNT_LOCKOUT_ATTEMPTS: Number(process.env.ACCOUNT_LOCKOUT_ATTEMPTS ?? 3),
  ACCOUNT_LOCKOUT_DURATION_HOURS: Number(
    process.env.ACCOUNT_LOCKOUT_DURATION_HOURS ?? 1,
  ),
  OTP_EXPIRY_MINUTES: Number(process.env.OTP_EXPIRY_MINUTES ?? 10),
  LATE_PENALTY_PERCENT: Number(process.env.LATE_PENALTY_PERCENT ?? 2),
  BILLING_DAY: Number(process.env.BILLING_DAY ?? 1),
  BCRYPT_COST_FACTOR: 12,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  WALK_IN_APPROVAL_TIMEOUT_MINUTES: 5,
} as const;
